In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv("receivers_data.csv")

In [ ]:
df.head(10)

,Receiver_ID,Name,Type,City,Contact
0,1,Donald Gomez,Shelter,Port Carlburgh,9559225295
1,2,Laurie Ramos,Individual,Lewisburgh,7610421570
2,3,Ashley Mckee,NGO,South Randalltown,6910230094856
3,4,Erika Rose,NGO,South Shaneville,8296491111
4,5,John Romero,Individual,Bakerport,0674910154
5,6,Mandy Sutton PhD,Shelter,East Sharimouth,6827775357
6,7,Kenneth Baker,NGO,South Edwinborough,12664563864071
7,8,James Perez,Charity,Benjaminburgh,19867486688
8,9,Emily Turner,Shelter,West Robert,0016310226157520
9,10,Mary Salazar,NGO,Wrightland,001187333751811395

In [ ]:
def clean_contact(contact):
    if isinstance(contact, str):
        return ''.join(filter(str.isdigit, contact))
    return contact

df['Contact'] = df['Contact'].apply(clean_contact)

In [ ]:
df.head(10)

,Receiver_ID,Name,Type,City,Contact
0,1,Donald Gomez,Shelter,Port Carlburgh,9559225295
1,2,Laurie Ramos,Individual,Lewisburgh,7610421570
2,3,Ashley Mckee,NGO,South Randalltown,6910230094856
3,4,Erika Rose,NGO,South Shaneville,8296491111
4,5,John Romero,Individual,Bakerport,0674910154
5,6,Mandy Sutton PhD,Shelter,East Sharimouth,6827775357
6,7,Kenneth Baker,NGO,South Edwinborough,12664563864071
7,8,James Perez,Charity,Benjaminburgh,19867486688
8,9,Emily Turner,Shelter,West Robert,0016310226157520
9,10,Mary Salazar,NGO,Wrightland,001187333751811395

In [ ]:
df.head()

   Receiver_ID          Name        Type               City        Contact
0            1  Donald Gomez     Shelter     Port Carlburgh     9559225295
1            2  Laurie Ramos  Individual         Lewisburgh     7610421570
2            3  Ashley Mckee         NGO  South Randalltown  6910230094856
3            4    Erika Rose         NGO   South Shaneville     8296491111
4            5   John Romero  Individual          Bakerport     0674910154

In [ ]:
df.isnull().sum()

Receiver_ID    0
Name           0
Type           0
City           0
Contact        0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(1000, 5)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(1000, 5)

In [ ]:
df.dtypes

Receiver_ID     int64
Name           object
Type           object
City           object
Contact        object
dtype: object

In [ ]:
df.to_csv('clean_receivers_data.csv', index=False)

In [ ]:
df1 = pd.read_csv("providers_data.csv")

In [ ]:
df1.head(10)

,Provider_ID,Name,Type,Address,City,Contact
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions\nAndreamouth, OK ...",New Jessica,+1-600-220-0480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream\nWelchtown, OR 27136",East Sheena,+1-925-283-8901x6297
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507\nGuzmanchester, W...",Lake Jesusview,001-517-295-2206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409\nPort Jesus, IA 61188",Mendezmouth,556.944.8935x401
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319\nSaraborough, MA 53978",Valentineside,193.714.6577
5,6,Lawson-Walters,Grocery Store,"1889 Barnes Gateway\nAdamview, ID 87971",Shannonside,144-860-6074x60544
6,7,Ortiz-Lee,Restaurant,"1842 Villarreal Shores\nWilliamfort, CT 44529",Lake Christopherburgh,(563)889-7190
7,8,Curtis-Lewis,Supermarket,"4770 Miller Light Suite 260\nNew Charlesville,...",Washingtonville,+1-521-027-8120x3301
8,9,Nguyen Inc,Supermarket,"169 Scott Keys Suite 000\nEast Michelle, HI 57025",Tinamouth,898-609-2609x844
9,10,"Hall, Nguyen and Martinez",Catering Service,"71458 Mark Field Apt. 252\nNorth Alexland, TX ...",West Cherylfort,(740)949-2480x40566

In [ ]:
df1.dtypes

Provider_ID     int64
Name           object
Type           object
Address        object
City           object
Contact        object
dtype: object

In [ ]:
df1.isnull().sum()

Provider_ID    0
Name           0
Type           0
Address        0
City           0
Contact        0
dtype: int64

In [ ]:
df1.duplicated().sum()

np.int64(0)

In [ ]:
df1.drop_duplicates(inplace=True)

In [ ]:
df1['Contact'] = df1['Contact'].apply(clean_contact)

In [ ]:
df1.head()

,Provider_ID,Name,Type,Address,City,Contact
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions\nAndreamouth, OK ...",New Jessica,16002200480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream\nWelchtown, OR 27136",East Sheena,192528389016297
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507\nGuzmanchester, W...",Lake Jesusview,0015172952206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409\nPort Jesus, IA 61188",Mendezmouth,5569448935401
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319\nSaraborough, MA 53978",Valentineside,1937146577

In [ ]:
def clean_address(address):
    if isinstance(address, str):
        # Replace newlines with comma and space, then remove multiple spaces
        cleaned_address = address.replace('\n', ', ').strip()
        # Replace multiple spaces with a single space
        cleaned_address = ' '.join(cleaned_address.split())
        return cleaned_address
    return address

df1['Address'] = df1['Address'].apply(clean_address)

In [ ]:
df1.head()

,Provider_ID,Name,Type,Address,City,Contact
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions, Andreamouth, OK ...",New Jessica,16002200480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream, Welchtown, OR 27136",East Sheena,192528389016297
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507, Guzmanchester, W...",Lake Jesusview,0015172952206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409, Port Jesus, IA 61188",Mendezmouth,5569448935401
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319, Saraborough, MA 53978",Valentineside,1937146577

In [ ]:
df1.to_csv('clean_providers_data.csv', index=False)

In [ ]:
df2 = pd.read_csv("food_listings_data.csv")

In [ ]:
df2.head(10)

,Food_ID,Food_Name,Quantity,Expiry_Date,Provider_ID,Provider_Type,Location,Food_Type,Meal_Type
0,1,Bread,43,3/17/2025,110,Grocery Store,South Kellyville,Non-Vegetarian,Breakfast
1,2,Soup,22,3/24/2025,791,Grocery Store,West James,Non-Vegetarian,Dinner
2,3,Fruits,46,3/28/2025,478,Catering Service,Lake Regina,Vegan,Breakfast
3,4,Fruits,15,3/16/2025,930,Restaurant,Kellytown,Vegan,Lunch
4,5,Soup,14,3/19/2025,279,Restaurant,Garciaport,Vegan,Dinner
5,6,Vegetables,4,3/24/2025,378,Supermarket,South Johnshire,Vegan,Snacks
6,7,Dairy,29,3/25/2025,268,Grocery Store,Nolanmouth,Vegan,Dinner
7,8,Rice,49,3/28/2025,343,Catering Service,South Christopherborough,Vegetarian,Lunch
8,9,Bread,46,3/25/2025,47,Supermarket,East Andrewland,Non-Vegetarian,Snacks
9,10,Rice,41,3/20/2025,528,Supermarket,Markport,Vegan,Dinner

In [ ]:
df2.dtypes

Food_ID           int64
Food_Name        object
Quantity          int64
Expiry_Date      object
Provider_ID       int64
Provider_Type    object
Location         object
Food_Type        object
Meal_Type        object
dtype: object

In [ ]:
df2.isnull().sum()

Food_ID          0
Food_Name        0
Quantity         0
Expiry_Date      0
Provider_ID      0
Provider_Type    0
Location         0
Food_Type        0
Meal_Type        0
dtype: int64

In [ ]:
df2.duplicated().sum()

np.int64(0)

In [ ]:
df3 = pd.read_csv('claims_data.csv')

In [ ]:
df3.head()

   Claim_ID  Food_ID  Receiver_ID     Status        Timestamp
0         1      164          908    Pending    3/5/2025 5:26
1         2      353          391  Cancelled  3/11/2025 10:24
2         3      626          492  Completed   3/21/2025 0:59
3         4       61          933  Cancelled    3/4/2025 9:08
4         5      345          229    Pending  3/14/2025 15:17

In [ ]:
df3.dtypes

Claim_ID        int64
Food_ID         int64
Receiver_ID     int64
Status         object
Timestamp      object
dtype: object

In [ ]:
df3.isnull().sum()

Claim_ID       0
Food_ID        0
Receiver_ID    0
Status         0
Timestamp      0
dtype: int64

In [ ]:
df3.drop_duplicates(inplace=True)

In [ ]:
providers = pd.read_csv("clean_providers_data.csv")
receivers = pd.read_csv("clean_receivers_data.csv")
food = pd.read_csv("food_listings_data.csv")
claims = pd.read_csv("claims_data.csv")

In [ ]:
import plotly.express as px
import plotly.graph_objects as go

## **Univariate**

In [ ]:
# 1. Provider Type Distribution

fig = px.histogram(
    providers,
    x="Type",
    color="Type",
    title="Provider Type Distribution"
)

fig.update_layout(
    xaxis_title="Provider Type",
    yaxis_title="Count"
)

fig.show()

In [ ]:
# 2. Receiver Type Distribution

fig = px.pie(
    receivers,
    names="Type",
    title="Receiver Type Distribution",
    hole=0.4
)

fig.show()

In [ ]:
# 3. Food Type Distribution

fig = px.bar(
    food["Food_Type"].value_counts().reset_index(),
    x="Food_Type",
    y="count",
    title="Food Type Distribution"
)

fig.show()

In [ ]:
# 4. Meal Type Distribution

fig = px.pie(
    food,
    names="Meal_Type",
    title="Meal Type Distribution"
)

fig.show()

## **Bivariate**

In [ ]:
# 5. City vs Food Listings
city_food = food.groupby("Location").size().reset_index(name="Listings")

fig = px.bar(
    city_food,
    x="Location",
    y="Listings",
    color="Listings",
    title="City vs Food Listings"
)

fig.show()

In [ ]:
# 6. Provider Type vs Quantity

provider_qty = food.groupby("Provider_Type")["Quantity"].sum().reset_index()

fig = px.bar(
    provider_qty,
    x="Provider_Type",
    y="Quantity",
    color="Quantity",
    title="Provider Type vs Quantity"
)

fig.show()

In [ ]:
# 8. Meal Type vs Quantity

meal_qty = food.groupby("Meal_Type")["Quantity"].sum().reset_index()

fig = px.bar(
    meal_qty,
    x="Meal_Type",
    y="Quantity",
    color="Quantity",
    title="Meal Type vs Quantity"
)

fig.show()

## **Multivariate**

In [ ]:
# 9. City + Provider Type + Quantity

city_provider = food.groupby(
    ["Location", "Provider_Type"]
)["Quantity"].sum().reset_index()

fig = px.sunburst(
    city_provider,
    path=["Location", "Provider_Type"],
    values="Quantity",
    title="City + Provider Type + Quantity"
)

fig.show()

In [ ]:
# 10. Food Type + Meal Type + Quantity

food_meal = food.groupby(
    ["Food_Type", "Meal_Type"]
)["Quantity"].sum().reset_index()

fig = px.treemap(
    food_meal,
    path=["Food_Type", "Meal_Type"],
    values="Quantity",
    title="Food Type + Meal Type + Quantity"
)

fig.show()

In [ ]:
# 11. Provider + Claims + Quantity

provider_claims = food.merge(
    claims,
    on="Food_ID"
)

provider_claims = provider_claims.groupby(
    "Provider_ID"
).agg(
    Claims=("Claim_ID", "count"),
    Quantity=("Quantity", "sum")
).reset_index()

fig = px.scatter(
    provider_claims,
    x="Claims",
    y="Quantity",
    size="Quantity",
    title="Provider Claims vs Quantity"
)

fig.show()

In [ ]:
# 12. Receiver + Claims + Quantity

receiver_claims = claims.merge(
    food,
    on="Food_ID"
)

receiver_claims = receiver_claims.groupby(
    "Receiver_ID"
).agg(
    Claims=("Claim_ID", "count"),
    Quantity=("Quantity", "sum")
).reset_index()

fig = px.scatter(
    receiver_claims,
    x="Claims",
    y="Quantity",
    size="Quantity",
    title="Receiver Claims vs Quantity"
)

fig.show()

In [ ]:
# 13. Claim Status Distribution

fig = px.pie(
    claims,
    names="Status",
    title="Claim Status Distribution",
    hole=0.5
)

fig.show()

In [ ]:
# 14. Top 10 Receivers

top_receivers = claims.groupby(
    "Receiver_ID"
).size().reset_index(name="Claims")

top_receivers = top_receivers.sort_values(
    "Claims",
    ascending=False
).head(10)

fig = px.bar(
    top_receivers,
    x="Receiver_ID",
    y="Claims",
    color="Claims",
    title="Top 10 Receivers"
)

fig.show()

In [ ]:
# 15. Top 10 Providers

top_providers = food.groupby(
    "Provider_ID"
)["Quantity"].sum().reset_index()

top_providers = top_providers.sort_values(
    "Quantity",
    ascending=False
).head(10)

fig = px.bar(
    top_providers,
    x="Provider_ID",
    y="Quantity",
    color="Quantity",
    title="Top 10 Providers"
)

fig.show()

In [ ]:
total_food = food["Quantity"].sum()
total_providers = providers["Provider_ID"].nunique()
total_receivers = receivers["Receiver_ID"].nunique()
total_claims = claims["Claim_ID"].nunique()

print("Total Food:", total_food)
print("Total Providers:", total_providers)
print("Total Receivers:", total_receivers)
print("Total Claims:", total_claims)

Total Food: 25794
Total Providers: 1000
Total Receivers: 1000
Total Claims: 1000